// Code generated by dagger-compiler.  Do not edit.
package com.sjtu.icarer.common.utils;

import dagger.internal.Binding;
import dagger.internal.Linker;
import dagger.internal.StaticInjection;

/**
 * A manager for {@code Ln}'s injections into static fields.
 */
public final class Ln$$StaticInjection extends StaticInjection {
  private Binding<Ln.BaseConfig> config;
  private Binding<Ln.Print> print;

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    config = (Binding<Ln.BaseConfig>) linker.requestBinding("com.sjtu.icarer.common.utils.Ln$BaseConfig", com.sjtu.icarer.common.utils.Ln.class, getClass().getClassLoader());
    print = (Binding<Ln.Print>) linker.requestBinding("com.sjtu.icarer.common.utils.Ln$Print", com.sjtu.icarer.common.utils.Ln.class, getClass().getClassLoader());
  }


  /**
   * Performs the injections of dependencies into static fields when requested by
   * the {@code dagger.ObjectGraph}.
   */
  @Override
  public void inject() {
    Ln.config = config.get();
    Ln.print = print.get();
  }

}
