// Code generated by dagger-compiler.  Do not edit.
package com.sjtu.icarer.service;

import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<IcarerService>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code IcarerService} and its
 * dependencies.
 *
 * Being a {@code Provider<IcarerService>} and handling creation and
 * preparation of object instances.
 */
public final class IcarerService$$InjectAdapter extends Binding<IcarerService>
    implements Provider<IcarerService> {
  private Binding<retrofit.RestAdapter> restAdapter;

  public IcarerService$$InjectAdapter() {
    super("com.sjtu.icarer.service.IcarerService", "members/com.sjtu.icarer.service.IcarerService", NOT_SINGLETON, IcarerService.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    restAdapter = (Binding<retrofit.RestAdapter>) linker.requestBinding("retrofit.RestAdapter", IcarerService.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(restAdapter);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<IcarerService>}.
   */
  @Override
  public IcarerService get() {
    IcarerService result = new IcarerService(restAdapter.get());
    return result;
  }

}
