// Code generated by dagger-compiler.  Do not edit.
package com.sjtu.icarer;

import dagger.internal.ModuleAdapter;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class RootModule$$ModuleAdapter extends ModuleAdapter<RootModule> {
  private static final String[] INJECTS = { };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { com.sjtu.icarer.AndroidModule.class, com.sjtu.icarer.IcarerModule.class, };

  public RootModule$$ModuleAdapter() {
    super(com.sjtu.icarer.RootModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  @Override
  public RootModule newModule() {
    return new com.sjtu.icarer.RootModule();
  }
}
